# Generated by Django 5.1.7 on 2025-03-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.TextField(verbose_name='Список блюд (пример: хлеб-100, борщ-200)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('готово', 'Готово'), ('оплачено', 'Оплачено')], default='в ожидании', max_length=20, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(verbose_name='Номер стола'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость'),
        ),
    ]
