# Generated by Django 5.1.7 on 2026-03-02 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_item_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('закуски', 'Закуски'), ('салаты', 'Салаты'), ('супы', 'Супы'), ('горячее', 'Горячие блюда'), ('гарниры', 'Гарниры'), ('напитки', 'Напитки'), ('десерты', 'Десерты'), ('прочее', 'Прочее')], default='прочее', max_length=50, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание блюда, состав', verbose_name='Описание/состав'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступно к заказу'),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
