# Generated by Django 5.2.11 on 2026-03-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_options_remove_item_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('в ожидании', 'В ожидании'), ('готово', 'Готово'), ('оплачено', 'Оплачено')], max_length=20, verbose_name='Статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Кто изменил')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История заказа',
                'verbose_name_plural': 'История заказов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
