# Generated by Django 5.2.12 on 2026-03-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Фото блюда'),
        ),
    ]
